name: deploy

on:
  push:
    branches:
      - main
      - feature/push_images_to_ecr

env:
  AWS_REGION: ap-northeast-1

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest
    steps:
      - name: Configure aws credentials for OIDC
        #if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION  }}
          role-session-name: GitHubActions-${{ github.run_id }}
        run: aws sts get-caller-identity  